# Generated by Django 3.1 on 2022-03-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_model',
            new_name='variation_value',
        ),
    ]
